### PR TITLE
System dependencies for cob_read_text, updates to cob_fiducials and surface_classification

### PR DESCRIPTION
**Pull request by ipa-rmb**
- major contribution is the switch to system dependencies in cob_read_text
- contains some bugfixes and code cleaning for cob_fiducials
- updates to cob_surface_classification are work in progress and only relevant to me - no in-depth review necessary if Travis is happy

### CODE REVIEW

**Comment by fmessmer** [comment]
Thanks @ipa-rmb for sync'ing
Can't say much about the functionality, but formally I can't find anything to complain :wink: 
Still, Travis CI needs fixing...you probably need to add something to the both `.travis.rosinstall` and `.travis.rosinstall.kinetic` file in order to find `cob_3d_segmentation` (i.e. https://github.com/ipa320/cob_environment_perception)... or @ipa-josh's branch...

**Comment by fmessmer** [comment]
@ipa-rmb 
I don't think it's a matter of `travis_wait`...or parallel jobs....
For public repos you are bound to the [Travis TimeOuts](https://docs.travis-ci.com/user/customizing-the-build/#Build-Timeouts)

**Comment by ipa-rmb** [comment]
But indeed the travis_wait did the job. Before I got the timeout errors, now with travis_wait 60, i.e. 60 minutes, it eventually succeeded. Now we can merge, can't we?

**Comment by fmessmer** [comment]
How does this pass Travis with https://github.com/ipa320/cob_environment_perception/pull/38 failing due to a Timeout as `cob_environment_perception` (and many other repos) are included in the `.rosinstall` file?

**Comment by ipa-rmb** [comment]
I don't know, but thats the way it is.

**Comment by ipa-rmb** [comment]
@ipa-fxm can I merge this one now?

**Comment by ipa-rmb** [comment]
He said yes.

**Pull request merged**
