### PR TITLE
added publisher for fiducial marker detection array with id

### PR DESCRIPTION
**Pull request by Equanox**

### CODE REVIEW

**Comment by floweisshardt** [comment]
@ipa-jsf can you comment and merge/deny on this PR?

**Comment by ipa-jsf** [comment]
Please do not modify the launch file and add a clear comment why you needed to add a new publisher

**Comment by mgruhler** [comment]
@Equanox What's the status on this?

**Comment by Equanox** [comment]
We use this publisher in the Seneka project. I think it is more comfortable having all detected markers in one message discriminable by id. The publishing over TF is not really helpful in our case due to the missing marker id and the necessity to check for timestamps.

I see a small problem. This PR is only working with https://github.com/ipa320/cob_perception_common groovy_dev_catkin branch due to the commit https://github.com/ipa320/cob_perception_common/pull/15 which was NOT merged to actual branches.

Maybe we can add the small change from https://github.com/ipa320/cob_perception_common/pull/15 also to the cob_perception_common/groovy_dev branch and merge cob_perception_common/grovy_dev_catkin to cob_perception_common/hydro_dev and cob_perception_common/indigo_dev?

From my point of view the suggested changes in  https://github.com/ipa320/cob_perception_common shouldn't affect other projects.

**Comment by floweisshardt** [comment]
merging that to the recent hydro_dev and indigo_dev branches sounds reasonable to me. @ipa-rmb or @ipa-jsf can you please setup a pull request and merge that after reviewing?

**Comment by mgruhler** [comment]
@ipa-rmb @ipa-jsf please decide on what you are going to do with that...

**Comment by ipa-rmb** [comment]
@ipa-jsf Please review the work and do the merges.

**Comment by floweisshardt** [comment]
@ipa-jsf please comment, merge or close

**Comment by mgruhler** [comment]
YES!

**Pull request merged**
