### PR TITLE
Added install prerequisites

### PR DESCRIPTION
**Pull request by ipa-rmb**

### CODE REVIEW

**Comment by ipa-rmb** [comment]
By the way, is there a way to download other git repositories automatically, like the https://github.com/ipa320/cob_environment_perception.git needed here? Is there a way to tell rosdep install to download such missing repositories?

**Comment by ipa-rmb** [comment]
Apparently there is no such way to download repositories with rosdep install.

**Comment by floweisshardt** [comment]
there is a way: provide a `rosinstall` file which can even be used by travis

**Comment by ipa-rmb** [comment]
Thanks, that is what I added, but for rosinstall a normal user has to utilize another tool besides rosdep install, but Mathias confirmed that this is the only possible way: using both tools. Thanks for the suggestion, anyways.

**Comment by fmessmer** [comment]
You could use the following instructions in the README:

```
 - cd /path/to/catkin_workspace/src && git clone https://github.com/ipa320/cob_object_perception.git
 - cd /path/to/catkin_workspace/src && wstool init
 - cd /path/to/catkin_workspace/src && wstool merge /path/to/catkin_workspace/src/cob_object_perception/.travis.rosinstall
 - cd /path/to/catkin_workspace/src && wstool update
```
This will download all repos from the .travis.rosinstall file making sure that source dependencies are available in the workspace...then continue with the ```rosdep install....```

**Comment by ipa-rmb** [comment]
Thanks Felix, I will add this.

**Pull request merged**
