### PR TITLE
Hydro dev

### PR DESCRIPTION
**Pull request by ipa-jsf**
Catkinizing packages cob_object_perception
@ipa-fmw Please review
@ipa-mdl Please review

### CODE REVIEW

**Comment by floweisshardt** [comment]
@ipa-jsf just a short comment: did you delete all this packages by purpose?
@ipa-fxm: please have a look at the CMakeLists and package.xml

**Comment by ipa-jsf** [comment]
@ipa-fmw the deleted packages have been replaced with system dependencies. Seemd to be cleaner and easier.

**Comment by fmessmer** [comment]
there are some files missing...and some more catkin problems...@ipa-jsf is on it...

**Comment by ipa-jsf** [comment]
@ipa-fxm Added missing files and fixed some other bugs
Please also check catkinized dependecy cob_perception_data

**Comment by fmessmer** [comment]
the system dependencies are not specified correctly:
It says all dependencies are met (rosdep install --from-paths src -i -y), but e.g. libdmtx-dev is missing.
libdmtx-dev also needs to be added here: https://github.com/ros/rosdistro/blob/master/hydro/distribution.yaml
The same needs to be done for other required system dependencies!

Packages I had to install manually:
- libdmtx-dev (version 0.7.2-1build2)
- imagemagick (version 8:6.6.9.7-5ubuntu3) (I did this first, but I think...)
- libmagick++-dev (version 8:6.6.9.7-5ubuntu3) (...is the one you want!)
- ant (version 1.8.2-4build1)
- scons (version 2.1.0-1)

**Comment by fmessmer** [comment]
Warning found:

```
CMake Warning (dev) at cob_object_perception/cob_read_text/CMakeLists.txt:177 (add_executable):
  Policy CMP0003 should be set before this line.  Add code such as

    if(COMMAND cmake_policy)
      cmake_policy(SET CMP0003 NEW)
    endif(COMMAND cmake_policy)

  as early as possible but after the most recent call to
  cmake_minimum_required or cmake_policy(VERSION).  This warning appears
  because target "read_text_showPCD" links to some libraries for which the
  linker must search:

    -lm, dl

  and other libraries with known full path:

    /opt/ros/hydro/lib/libcv_bridge.so
    /usr/lib/libvtkCommon.so.5.8.0

  CMake is adding directories in the second list to the linker search path in
  case they are needed to find libraries from the first list (for backwards
  compatibility with CMake 2.4).  Set policy CMP0003 to OLD or NEW to enable
  or disable this behavior explicitly.  Run "cmake --help-policy CMP0003" for
  more information.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by fmessmer** [comment]
There are also some pcl and tf conversion related deprecation warnings!

**Comment by fmessmer** [comment]
Also check install tags
(All functionality should work when sourcing `<path-to-catkin-ws>/install/setup.bash` instead of `<path-to-catkin-ws>/devel/setup.bash`)

**Comment by ipa-jsf** [comment]
Issue 1:
Wrong link --> https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml
All dependencies are listed!

ToDo:
define dependencies so that `rosdep install --from-paths src -i -y` installs what is needed!

**Comment by ipa-jsf** [comment]
@ipa-fxm Fixed dependecies, install tags and cmake warning

**Comment by fmessmer** [comment]
Please add system dependencies in libzxing for the following packages:
- ant
- scons
- openjdk-6-jdk (required for `javac`; only jre is installed in Ubuntu by default)

**Comment by fmessmer** [comment]
And yet another deprecation warning:

```
In file included from /home/fxm/projects/hydro/care-o-bot/src/cob_object_perception/cob_read_text/ros/src/cob_read_text.cpp:14:0:
/usr/include/pcl-1.7/pcl/ros/conversions.h:44:2: warning: #warning The <pcl/ros/conversions.h> header is deprecated. please use <pcl/conversions.h> instead. [-Wcpp]
In file included from /usr/include/c++/4.6/backward/strstream:52:0,
                 from /usr/include/vtk-5.8/vtkIOStream.h:112,
                 from /usr/include/vtk-5.8/vtkSystemIncludes.h:40,
                 from /usr/include/vtk-5.8/vtkIndent.h:24,
                 from /usr/include/vtk-5.8/vtkObjectBase.h:43,
                 from /usr/include/vtk-5.8/vtkSmartPointerBase.h:26,
                 from /usr/include/vtk-5.8/vtkSmartPointer.h:23,
                 from /usr/include/pcl-1.7/pcl/visualization/point_cloud_geometry_handlers.h:48,
                 from /usr/include/pcl-1.7/pcl/visualization/point_cloud_handlers.h:41,
                 from /usr/include/pcl-1.7/pcl/visualization/common/actor_map.h:40,
                 from /usr/include/pcl-1.7/pcl/visualization/pcl_visualizer.h:47,
                 from /home/fxm/projects/hydro/care-o-bot/src/cob_object_perception/cob_read_text/ros/src/cob_read_text.cpp:18:
/usr/include/c++/4.6/backward/backward_warning.h:33:2: warning: #warning This file includes at least one deprecated or antiquated header which may be removed without further notice at a future date. Please use a non-deprecated interface with equivalent functionality instead. For a listing of replacement headers and interfaces, consult the file backward_warning.h. To disable this warning use -Wno-deprecated. [-Wcpp]
```

**Comment by fmessmer** [comment]
And another one:

```
In file included from /usr/include/c++/4.6/backward/strstream:52:0,
                 from /usr/include/vtk-5.8/vtkIOStream.h:112,
                 from /usr/include/vtk-5.8/vtkSystemIncludes.h:40,
                 from /usr/include/vtk-5.8/vtkIndent.h:24,
                 from /usr/include/vtk-5.8/vtkObjectBase.h:43,
                 from /usr/include/vtk-5.8/vtkSmartPointerBase.h:26,
                 from /usr/include/vtk-5.8/vtkSmartPointer.h:23,
                 from /usr/include/pcl-1.7/pcl/visualization/point_cloud_geometry_handlers.h:48,
                 from /usr/include/pcl-1.7/pcl/visualization/point_cloud_handlers.h:41,
                 from /usr/include/pcl-1.7/pcl/visualization/common/actor_map.h:40,
                 from /usr/include/pcl-1.7/pcl/visualization/pcl_visualizer.h:47,
                 from /home/fxm/projects/hydro/care-o-bot/src/cob_object_perception/cob_object_categorization/common/src/ObjectClassifier.cpp:35:
/usr/include/c++/4.6/backward/backward_warning.h:33:2: warning: #warning This file includes at least one deprecated or antiquated header which may be removed without further notice at a future date. Please use a non-deprecated interface with equivalent functionality instead. For a listing of replacement headers and interfaces, consult the file backward_warning.h. To disable this warning use -Wno-deprecated. [-Wcpp]
```

**Comment by fmessmer** [comment]
And two more:

```
/home/fxm/projects/hydro/care-o-bot/src/cob_object_perception/cob_object_recording/ros/src/object_recording.cpp: In member function ‘tf::Transform ObjectRecording::computeMarkerPose(const ConstPtr&)’:
/home/fxm/projects/hydro/care-o-bot/src/cob_object_perception/cob_object_recording/ros/src/object_recording.cpp:418:42: warning: ‘tf::Quaternion::Quaternion(const tfScalar&, const tfScalar&, const tfScalar&)’ is deprecated (declared at /opt/ros/hydro/include/tf/LinearMath/Quaternion.h:51) [-Wdeprecated-declarations]
/home/fxm/projects/hydro/care-o-bot/src/cob_object_perception/cob_object_recording/ros/src/object_recording.cpp: In member function ‘void ObjectRecording::computePerspective(const double&, const double&, const double&, tf::Transform&)’:
/home/fxm/projects/hydro/care-o-bot/src/cob_object_perception/cob_object_recording/ros/src/object_recording.cpp:522:70: warning: ‘tf::Quaternion::Quaternion(const tfScalar&, const tfScalar&, const tfScalar&)’ is deprecated (declared at /opt/ros/hydro/include/tf/LinearMath/Quaternion.h:51) [-Wdeprecated-declarations]
/home/fxm/projects/hydro/care-o-bot/src/cob_object_perception/cob_object_recording/ros/src/object_recording.cpp:524:47: warning: ‘tf::Quaternion::Quaternion(const tfScalar&, const tfScalar&, const tfScalar&)’ is deprecated (declared at /opt/ros/hydro/include/tf/LinearMath/Quaternion.h:51) [-Wdeprecated-declarations]
/home/fxm/projects/hydro/care-o-bot/src/cob_object_perception/cob_object_recording/ros/src/object_recording.cpp:526:46: warning: ‘tf::Quaternion::Quaternion(const tfScalar&, const tfScalar&, const tfScalar&)’ is deprecated (declared at /opt/ros/hydro/include/tf/LinearMath/Quaternion.h:51) [-Wdeprecated-declarations]
```

```
In file included from /home/fxm/projects/hydro/care-o-bot/src/cob_object_perception/cob_read_text/ros/src/cob_read_text.cpp:14:0:
/usr/include/pcl-1.7/pcl/ros/conversions.h:44:2: warning: #warning The <pcl/ros/conversions.h> header is deprecated. please use <pcl/conversions.h> instead. [-Wcpp]
```

**Comment by fmessmer** [comment]
One more observation:
After a first catkin_make, in libzxing the common/include folder is over-written by the downloaded source code. Thus, the placeholder file `README` gets deleted...

**Comment by ipa-jsf** [comment]
@ipa-fxm You find the needle in the code. Good work. I fixed the missing dependencies and the removal of the README file. 
@ipa-fxm@ipa-rmb The deprecation warnings will be fixed later, when by the owner of the source code

**Comment by fmessmer** [comment]
It looks good to me now and I was able to compile it (`catkin_make install`)
Thus, I think it can be merged now @ipa-jsf @ipa-fmw 

Next step would be to check the functionality is still as desired. @ipa-jsf @ipa-rmb 
Also, please check whether the functionality is given only using the `install space`. This would verify that install tags exist for all required files.

And finally, then try releasing....and fix all the problems reported by the build farm :smiley:

**Pull request merged**
