### PR TITLE
Multi distro travis

### PR DESCRIPTION
**Pull request by fmessmer**
@ipa-rmb @ipa-nhg FYI

### CODE REVIEW

**Comment by fmessmer** [comment]
Hmm, I don't like https://github.com/ipa320/cob_object_perception/pull/46/commits/71a9479954535d521116a05992ac04c68b4978e2 and also it does not fix:

```
Errors     << cob_marker:make /root/catkin_ws/logs/cob_marker/build.make.000.log

In file included from /root/catkin_ws/src/cob_object_perception/cob_marker/common/include/cob_marker/zxing/MagickBitmapSource.h:5:0,

                 from /root/catkin_ws/src/cob_object_perception/cob_marker/common/src/MagickBitmapSource.cpp:17:

/root/catkin_ws/devel/include/libzxing/LuminanceSource.h:23:34: fatal error: zxing/common/Counted.h: No such file or directory

 #include <zxing/common/Counted.h>

                                  ^

compilation terminated.

make[2]: *** [CMakeFiles/marker.dir/common/src/MagickBitmapSource.cpp.o] Error 1

make[2]: *** Waiting for unfinished jobs....

In file included from /root/catkin_ws/src/cob_object_perception/cob_marker/common/include/cob_marker/zxing/MagickBitmapSource.h:5:0,

                 from /root/catkin_ws/src/cob_object_perception/cob_marker/common/include/cob_marker/zxing/pc2magick.h:73,

                 from /root/catkin_ws/src/cob_object_perception/cob_marker/common/include/cob_marker/general_marker.h:82,

                 from /root/catkin_ws/src/cob_object_perception/cob_marker/ros/src/marker_action.cpp:78:

/root/catkin_ws/devel/include/libzxing/LuminanceSource.h:23:34: fatal error: zxing/common/Counted.h: No such file or directory

 #include <zxing/common/Counted.h>

                                  ^

compilation terminated.

make[2]: *** [CMakeFiles/marker.dir/ros/src/marker_action.cpp.o] Error 1

make[1]: *** [CMakeFiles/marker.dir/all] Error 2

make: *** [all] Error 2
```

The problem is that all the headers are referring to the headers as `<zxing/*>` which is in contrary to the package name `libzxing`...
I guess renaming the package would be an option....
@ipa-mdl do you know a better solution?

**Comment by mathias-luedtke** [comment]
What's the output if you just omit 71a9479?

**Comment by fmessmer** [comment]
well without, I get the same error but from within header files in `cob_marker` and `cob_texture_categorization`....

**Comment by mathias-luedtke** [comment]
`cob_marker` and `cob_texture_categorization` should not contain the 3rd party headers..

**Comment by fmessmer** [comment]
Solved it by copying and installing the headers into `zxing` folder (instead of `libzxing`) and adjusting the `CFG_EXTRAS` accordingly...This way, I do not need to touch any depending package...

**Review by ipa-nhg — APPROVED** [review]

**Comment by fmessmer** [comment]
this repo needs a specific `kinetic_dev` branch that fixes e.g. the issues with `cv`, `Eigen3`,...
tracking this in a separate issue #47

**Pull request merged**
